export {default as About } from './About/About';
export {default as Contact} from './Contact/Contact';
export {default as Header }from './Header/Header';
export {default as Landing} from './Landing/Landing';
export {default as Projects} from './Projects/Projects';
export {default as GoalStrive} from "./Projects/GoalStrive";
export {default as PackingAide} from "./Projects/PackingAide";
export {default as Photography} from "./Projects/Photography";
export {default as Quizzical} from "./Projects/Quizzical";
export {default as YoBurger} from "./Projects/YoBurger";
export {default as ToTopButton} from './ToTopButton';